p8105_hw2_rl3411
================
rl3411
2023-10-04

``` r
library(tidyverse)
library(readxl)
options(scipen = 999)
```

# Problem 1

Let’s first load and clean the `pols-month.csv` dataset.

``` r
pols_df <- 
  read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.integer(year),
    president = case_when(
      (prez_gop == 1 | prez_gop == 2) ~ "gop",
      (prez_dem == 1) ~ "dem"
    ) 
  ) |> 
  select(-c(prez_gop, prez_dem, day))
```

Now, let’s load and clean the `snp.csv` dataset.

``` r
snp_df <- 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  select(year, month, close) |> 
  mutate(
    month = month.name[as.numeric(month)],
    year = case_when(
      year < 23 ~ as.integer(paste0("20", year)),
      year > 23 ~ as.integer(paste0("19", year))
      )
    )
```

We now clean `unemployment.csv`.

``` r
uepm_df <- 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    month = month.name[match(month,month.abb)]
    ) |> 
  rename(year = Year)
```

Merging datasets together.

``` r
combined_df <- 
  left_join(pols_df, snp_df, by = join_by("year", "month")) |> 
  left_join(uepm_df, by = join_by("year", "month"))
```

The `pols_df` dataset contains 822 observations (i.e. rows) and 9
variables (i.e. columns). It shows the number of republican and
democratic governors, senators and representatives, as well as whether
the president was republican or democratic from January 1947 to June
2015.

The `snp_df` dataset contains 787 observations (i.e. rows) and 3
variables (i.e. columns). It shows the Standard and Poor’s stock market
index closing values from January 1950 to July 2015. As we are joining
`snp_df` **into** `pols_df`, we take the dimension of `pols_df` and
hence miss out the S&P closing price on July 2015.

The `uepm_df` dataset contains the monthly unemployment rates (in %)
from January 1948 to June 2015 and there are 816 observations in this
dataset.

# Problem 2

## Clean and organize data

``` r
mr_tw <- 
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", 
             sheet = "Mr. Trash Wheel",
             range = "B2:N586") |> 
  janitor::clean_names() |> 
  separate(date, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    month = month.name[as.numeric(month)],
    homes_powered = weight_tons * 500/30,
    dumpster = "Mr. Trash Wheel"
    ) 

prof_tw <- 
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", 
             sheet = "Professor Trash Wheel",
             range = "B2:M108") |> 
  janitor::clean_names() |> 
  separate(date, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    month = month.name[as.numeric(month)],
    homes_powered = weight_tons * 500/30,
    dumpster = "Professor Trash Wheel"
    ) 

gwynnda_tw <- 
  read_excel("data/202309 Trash Wheel Collection Data.xlsx", 
             sheet = "Gwynnda Trash Wheel",
             range = "B2:L157") |> 
  janitor::clean_names() |> 
  separate(date, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    month = month.name[as.numeric(month)],
    homes_powered = weight_tons * 500/30,
    dumpster = "Gwynnda Trash Wheel"
  ) 

# Combine data
dumpster_df <- 
  bind_rows(mr_tw, prof_tw) |> 
  bind_rows(gwynnda_tw)
```

There are 584 rows in the `mr_tw` dataset, 106 rows in the `prof_tw`
dataset, and 155 rows in the `gwynnda_tw` dataset. Thus, after combining
these three datasets (as `dumpster_df`), we get a total of 845 rows
(i.e. observations) in the combined dataset. The `mr_tw` dataset has
variables which are year, month, day, weight (in tons), volume (in cubic
yards), plastic bottles, polystyrene, cigarette butts, glass bottles,
plastic bags, wrappers, sports balls, and the number of homes powered.
There is also an identifier variable `dumpster` to indicate which
dumpster the data is referring to. The `prof_tw` has one less variable
than `mr_tw` as it has no data on sports balls. The `gwynnda_tw` dataset
has two less variables than `mr_tw`, as it has no data on sports balls
and glass bottles. These missing data have been indicated by NA.

|    Variables     | Mr. Trash Wheel | Professor Trash Wheel | Gwynnda Trash Wheel |
|:----------------:|:---------------:|:---------------------:|:-------------------:|
| Weight (in tons) |     1875.1      |        216.26         |       451.65        |

The total weight of trash collected by Professor Trash Wheel was 216.26
tons. By comparing the total weights, Mr. Trash Wheel has collected the
heaviest amount of trash at 1875.1 tons, followed by Gwynnda Trash Wheel
at 451.65 tons and Professor Trash Wheel. The total number of cigarette
butts collected by Gwynnda in July of 2021 was 16300.

# Problem 3

``` r
mci_baseline_df <- 
  read_csv("data/mci_baseline.csv") |>
  janitor::row_to_names(row_number = 1) |> 
  janitor::clean_names() |> 
  mutate(
    sex = case_match( 
      sex,
      "1" ~ "male",
      "0" ~ "female"
    ),
    apoe4 = case_match(
      apoe4,
      "1" ~ "carrier",
      "0" ~ "non-carrier"
    ),
    age_at_onset = as.numeric(age_at_onset),
    id = as.numeric(id),
    current_age = as.numeric(current_age),
    education = as.numeric(education)
  ) |> 
  filter((current_age < age_at_onset) | is.na(age_at_onset))
```

When importing this dataset, the column names include notes on each
variable and the correct variable names were moved to the next row in
the dataset. To change this, we use the `row_to_names()` function in the
`janitor` package. To encode `sex` appropriately, we code 1 as male and
0 as female. To encode `apoe4` appropriately, we code 1 as carrier and 0
as non-carrier. We also remove any participants who do not meet the
stated inclusion criteria, i.e. we remove participants whose MCI onset
appears to predate enrollment in the study. The numeric variables were
also imported as characters, hence we use `as.numeric()` to make the
conversion, which also automatically sets the onset ages “.” as NAs.

483 participants were recruited, of which 4 were removed as they did not
meet the stated inclusion criteria, leaving us with 479 participants.
Among these participants, 71 of them developed MCI. The average baseline
age is 65. Out of the 210 women in our dataset, 63 of them are APOE4
carriers.

``` r
mci_amyloid_df <- 
  read_csv("data/mci_amyloid.csv") |>
  janitor::row_to_names(row_number = 1) |> 
  janitor::clean_names() |> 
  rename(id = study_id,
         year_0 = baseline,
         year_2 = time_2,
         year_4 = time_4,
         year_6 = time_6,
         year_8 = time_8) |> 
    mutate(
    across(where(is.character), ~ na_if(., "Na")),
    id = as.numeric(id)
    ) |> 
  pivot_longer(
    year_0:year_8,
    names_to = "timepoint",
    values_to = "biomarker"
  ) 
```

In the `mci_amyloid_df` dataset, similar to the baseline data, we use
the `row_to_names()` function to set variable names correctly. Some of
the NAs were coded as “Na”, these were replaced with `NA`. Furthermore,
we rename the variables into years 0, 2, 4, 6, 8 as it is more
informative that naming them as `time_`. We also rename the `study_id`
variable to `id` for consistency with the baseline dataframe. Lastly, we
pivot the dataset to view the biomarker values longitudinally.

## Comparing `mci_baseline_df` and `mci_amyloid_df`

``` r
id_in_baseline = 
  anti_join(mci_baseline_df, mci_amyloid_df) # to see those in baseline not in amyloid

id_in_amyloid = 
  anti_join(mci_amyloid_df, mci_baseline_df) # to see those in amyloid not in baseline
```

There are 8 participants who are in `mci_baseline_df` but not in
`mci_amyloid_df`.

``` r
id_in_baseline[[1]]
```

    ## [1]  14  49  92 179 268 304 389 412

There are 16 participants who are in `mci_amyloid_df` but not in
`mci_baseline_df`.

``` r
unique(id_in_amyloid[[1]])
```

    ##  [1]  72 234 283 380 484 485 486 487 488 489 490 491 492 493 494 495

Now, we combine the demographic and biomarker datasets so that only
participants who appear in both datasets are retained.

``` r
mci_df <- inner_join(mci_baseline_df, mci_amyloid_df)
```

In summary, there are 495 IDs in total, and 8 are only in the baseline
dataset and 16 are only in the amyloid dataframe. But only taking those
that remain in both, we only have 471 patients left.

## Export MCI data

``` r
write_csv(mci_df, file = "MCI dataset.csv")
```
