---
title: "p8105_hw2_rl3411"
author: "rl3411"
date: "`r Sys.Date()`"
output: github_document
---

```{r, message = F}
library(tidyverse)
```

# Problem 1

Let's first load and clean the `pols-month.csv` dataset.
```{r, message = F}
pols_df <- 
  read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    month = month.name[as.numeric(month)],
    president = case_when(
      (prez_gop == 1 | prez_gop == 2) ~ "gop",
      (prez_dem == 1) ~ "dem"
    ) 
  ) |> 
  select(-c(prez_gop, prez_dem, day))
```

Now, let's load and clean the `snp.csv` dataset.

```{r, message = F}
snp_df <- 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  select(year, month, close) |> 
  mutate(
    month = month.name[as.numeric(month)],
    year = case_when(
      year < 23 ~ as.integer(paste0("20", year)),
      year > 23 ~ as.integer(paste0("19", year))
      )
    )
```

We now clean `unemployment.csv`.

```{r, message = F}
uepm_df <- 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "percentage"
  ) |> 
  mutate(
    month = month.name[match(month,month.abb)]
    ) |> 
  rename(year = Year)
```




